# Generated by Django 5.2.6 on 2025-10-04 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendarTrilhas', '0001_initial'),
        ('usuarioComun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomun',
            name='trilhaUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recomendarTrilhas.trilha'),
        ),
    ]
