# Generated by Django 5.2.6 on 2025-10-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendarTrilhas', '0003_capitulo_duracao_horas_video'),
        ('usuarioComun', '0002_usuariocomun_trilhauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocomun',
            name='trilhaUser',
        ),
        migrations.AddField(
            model_name='usuariocomun',
            name='trilhaUser',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='recomendarTrilhas.trilha'),
        ),
    ]
