# Generated by Django 5.2.6 on 2025-10-31 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioComun', '0003_remove_usuariocomun_trilhauser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioComun.usuariocomun')),
            ],
        ),
    ]
