# Generated by Django 5.2.6 on 2025-10-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendarTrilhas', '0001_initial'),
        ('usuarioComun', '0002_usuariocomun_trilhauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProgressoCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendarTrilhas.capitulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioComun.usuariocomun')),
            ],
            options={
                'unique_together': {('usuario', 'capitulo')},
            },
        ),
    ]
