# Generated by Django 5.2.6 on 2025-10-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendarTrilhas', '0002_capitulo_ordem_progressocapitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='duracao_horas_video',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
