# Generated by Django 5.2.6 on 2025-10-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendarTrilhas', '0003_capitulo_duracao_horas_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressocapitulo',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
