# Generated by Django 5.2.6 on 2025-10-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendarTrilhas', '0004_progressocapitulo_pontuacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trilha',
            options={'permissions': [('acessar_trilha', 'Pode acessar trilhas recomendadas')]},
        ),
    ]
