# Generated by Django 5.2.6 on 2025-10-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendarTrilhas', '0005_alter_trilha_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trilha',
            options={},
        ),
    ]
