# Generated by Django 5.2.6 on 2025-11-08 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendarTrilhas', '0006_alter_trilha_options'),
        ('usuarioComun', '0004_nivelconhecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_assistido', models.PositiveIntegerField(default=0)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendarTrilhas.capitulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioComun.usuariocomun')),
            ],
        ),
    ]
